// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:ef88d852-269c-4766-a357-f76b6689c87f",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_8aeKdfDgJ",
    "aws_user_pools_web_client_id": "5uhd9b80cudtj65mahngf38r0h",
    "aws_mobile_analytics_app_id": "e973ff660e044e39a3cdecb2eda71ca7",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
