// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:bab28792-e97f-4b47-a87f-367cb0b9b4d6",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_KyA9bf33G",
    "aws_user_pools_web_client_id": "45h4tnvif0915lpig62vvl6dv5"
};


export default awsmobile;
