// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:ebe64176-8569-4b81-ba21-aac196869070",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_SVfHB98Ij",
    "aws_user_pools_web_client_id": "6qndrq2b85vitsebj6hlv43vse",
    "aws_appsync_graphqlEndpoint": "https://sjbhlgntrbbxforo5ud7xiey44.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
