// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:7fb92488-f8e3-4c20-a544-0f79a7c17688",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Oz0TBdumO",
    "aws_user_pools_web_client_id": "26is2tdmu2m3c4v3i6cs4dnngf",
    "aws_appsync_graphqlEndpoint": "https://znl6bes7jbc5jimckchites5de.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
