projects:
  graphqlnoteapp:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: xc225jgl7jaqzk366jq3qpefoy
      endpoints:
        prod: >-
          https://znl6bes7jbc5jimckchites5de.appsync-api.us-west-2.amazonaws.com/graphql
